function Rock_Mass_Rating_Matlab_Code()

    % Close any existing RMR GUI figures from previous runs
    existingFigs = findall(0, 'Type', 'figure', 'Name', 'Tunnel Rock Mass Rating (RMR) Calculator');
    if ~isempty(existingFigs)
        close(existingFigs);
    end
    
    % Create main figure with enhanced appearance
    fig = figure('Name', 'Tunnel Rock Mass Rating (RMR) Calculator', ...
                 'NumberTitle', 'off', ...
                 'Position', [200, 100, 1000, 800], ...
                 'Resize', 'on', ...
                 'MenuBar', 'none', ...
                 'ToolBar', 'none', ...
                 'Color', [0.94, 0.94, 0.94], ...
                 'ResizeFcn', @resizeCallback);
    
    % Initialize data structure
    data = struct();
    
    % Create main panels
    createInputPanel();
    createResultsPanel();
    createButtonPanel();
    
    % Initialize GUI
    updateCalculations();
    
    function createInputPanel()
    % Main input panel with enhanced styling
    data.inputPanel = uipanel('Parent', fig, ...
                        'Title', 'RMR Parameters', ...
                        'FontSize', 14, ...
                        'FontWeight', 'bold', ...
                        'BackgroundColor', [0.97, 0.97, 0.97], ...
                        'ForegroundColor', [0.2, 0.3, 0.5], ...
                        'BorderType', 'beveledin', ...
                        'BorderWidth', 2, ...
                        'Units', 'normalized', ...
                        'Position', [0.02, 0.35, 0.96, 0.60]);
    
    % Parameter 1: Rock Strength
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', '1. Uniaxial Compressive Strength (MPa):', ...
             'FontSize', 11, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.85, 0.35, 0.06], ...
             'HorizontalAlignment', 'left');
    
    data.ucs_edit = uicontrol('Parent', data.inputPanel, 'Style', 'edit', ...
                             'String', '50', ...
                             'FontSize', 10, ...
                             'BackgroundColor', [1, 1, 1], ...
                             'Units', 'normalized', ...
                             'Position', [0.38, 0.85, 0.12, 0.06], ...
                             'Callback', @updateCalculations);
    
    data.ucs_text = uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
                             'String', 'Rating: 7', ...
                             'FontSize', 10, 'FontWeight', 'bold', ...
                             'BackgroundColor', [0.97, 0.97, 0.97], ...
                             'ForegroundColor', [0, 0.6, 0], ...
                             'Units', 'normalized', ...
                             'Position', [0.52, 0.85, 0.15, 0.06], ...
                             'HorizontalAlignment', 'left');
    
    % Parameter 2: RQD
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', '2. Rock Quality Designation - RQD (%):', ...
             'FontSize', 11, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.75, 0.35, 0.06], ...
             'HorizontalAlignment', 'left');
    
    data.rqd_edit = uicontrol('Parent', data.inputPanel, 'Style', 'edit', ...
                             'String', '75', ...
                             'FontSize', 10, ...
                             'BackgroundColor', [1, 1, 1], ...
                             'Units', 'normalized', ...
                             'Position', [0.38, 0.75, 0.12, 0.06], ...
                             'Callback', @updateCalculations);
    
    data.rqd_text = uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
                             'String', 'Rating: 13', ...
                             'FontSize', 10, 'FontWeight', 'bold', ...
                             'BackgroundColor', [0.97, 0.97, 0.97], ...
                             'ForegroundColor', [0, 0.6, 0], ...
                             'Units', 'normalized', ...
                             'Position', [0.52, 0.75, 0.15, 0.06], ...
                             'HorizontalAlignment', 'left');
    
    % Parameter 3: Joint Spacing
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', '3. Joint Spacing (m):', ...
             'FontSize', 11, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.65, 0.35, 0.06], ...
             'HorizontalAlignment', 'left');
    
    data.js_edit = uicontrol('Parent', data.inputPanel, 'Style', 'edit', ...
                            'String', '0.3', ...
                            'FontSize', 10, ...
                            'BackgroundColor', [1, 1, 1], ...
                            'Units', 'normalized', ...
                            'Position', [0.38, 0.65, 0.12, 0.06], ...
                            'Callback', @updateCalculations);
    
    data.js_text = uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
                            'String', 'Rating: 10', ...
                            'FontSize', 10, 'FontWeight', 'bold', ...
                            'BackgroundColor', [0.97, 0.97, 0.97], ...
                            'ForegroundColor', [0, 0.6, 0], ...
                            'Units', 'normalized', ...
                            'Position', [0.52, 0.65, 0.15, 0.06], ...
                            'HorizontalAlignment', 'left');
    
    % Parameter 4: Joint Condition
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', '4. Joint Condition:', ...
             'FontSize', 11, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.55, 0.25, 0.06], ...
             'HorizontalAlignment', 'left');
    
    joint_conditions = {'Very rough, unweathered, tight (30)', ...
                       'Slightly rough, slightly weathered (25)', ...
                       'Slightly rough, highly weathered (20)', ...
                       'Slickensided or gouge <5mm (10)', ...
                       'Soft gouge >5mm (0)'};
    
    data.jc_popup = uicontrol('Parent', data.inputPanel, 'Style', 'popupmenu', ...
                             'String', joint_conditions, ...
                             'Value', 2, ...
                             'FontSize', 10, ...
                             'BackgroundColor', [1, 1, 1], ...
                             'Units', 'normalized', ...
                             'Position', [0.28, 0.55, 0.45, 0.06], ...
                             'Callback', @updateCalculations);
    
    % Joint Condition Rating Display
    data.jc_text = uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
                            'String', 'Rating: 25', ...
                            'FontSize', 10, 'FontWeight', 'bold', ...
                            'BackgroundColor', [0.97, 0.97, 0.97], ...
                            'ForegroundColor', [0, 0.6, 0], ...
                            'Units', 'normalized', ...
                            'Position', [0.75, 0.55, 0.15, 0.06], ...
                            'HorizontalAlignment', 'left');
    
    % Parameter 5: Groundwater Condition
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', '5. Groundwater Condition:', ...
             'FontSize', 11, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.45, 0.25, 0.06], ...
             'HorizontalAlignment', 'left');
    
    water_conditions = {'Completely dry (15)', ...
                       'Damp (10)', ...
                       'Wet (7)', ...
                       'Dripping (4)', ...
                       'Flowing (0)'};
    
    data.gw_popup = uicontrol('Parent', data.inputPanel, 'Style', 'popupmenu', ...
                             'String', water_conditions, ...
                             'Value', 2, ...
                             'FontSize', 10, ...
                             'BackgroundColor', [1, 1, 1], ...
                             'Units', 'normalized', ...
                             'Position', [0.28, 0.45, 0.45, 0.06], ...
                             'Callback', @updateCalculations);
    
    % Groundwater Condition Rating Display
    data.gw_text = uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
                            'String', 'Rating: 10', ...
                            'FontSize', 10, 'FontWeight', 'bold', ...
                            'BackgroundColor', [0.97, 0.97, 0.97], ...
                            'ForegroundColor', [0, 0.6, 0], ...
                            'Units', 'normalized', ...
                            'Position', [0.75, 0.45, 0.15, 0.06], ...
                            'HorizontalAlignment', 'left');
    
    % Parameter 6: Joint Orientation Adjustment for Tunnels
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', '6. Joint Orientation Adjustment for Tunnels:', ...
             'FontSize', 11, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.35, 0.35, 0.06], ...
             'HorizontalAlignment', 'left');
    
    % Tunnel Azimuth input
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', 'Tunnel Azimuth (°):', ...
             'FontSize', 10, ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.28, 0.15, 0.05], ...
             'HorizontalAlignment', 'left');
    
    data.tunnel_azimuth_edit = uicontrol('Parent', data.inputPanel, 'Style', 'edit', ...
                                        'String', '00', ...
                                        'FontSize', 10, ...
                                        'BackgroundColor', [1, 1, 1], ...
                                        'Units', 'normalized', ...
                                        'Position', [0.18, 0.28, 0.08, 0.05]);
    
    % Joint Dip input
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', 'Joint Dip (°):', ...
             'FontSize', 10, ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.28, 0.28, 0.12, 0.05], ...
             'HorizontalAlignment', 'left');
    
    data.joint_dip_edit = uicontrol('Parent', data.inputPanel, 'Style', 'edit', ...
                                   'String', '45', ...
                                   'FontSize', 10, ...
                                   'BackgroundColor', [1, 1, 1], ...
                                   'Units', 'normalized', ...
                                   'Position', [0.41, 0.28, 0.08, 0.05]);
    
    % Joint Dip Direction input
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', 'Joint Dip Direction (°):', ...
             'FontSize', 10, ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.51, 0.28, 0.18, 0.05], ...
             'HorizontalAlignment', 'left');
    
    data.joint_dip_direction_edit = uicontrol('Parent', data.inputPanel, 'Style', 'edit', ...
                                             'String', '180', ...
                                             'FontSize', 10, ...
                                             'BackgroundColor', [1, 1, 1], ...
                                             'Units', 'normalized', ...
                                             'Position', [0.70, 0.28, 0.08, 0.05]);
    
    % Show Visualization Checkbox
    data.show_visualization_checkbox = uicontrol('Parent', data.inputPanel, 'Style', 'checkbox', ...
                                               'String', 'Show Visualization', ...
                                               'Value', 1, ...
                                               'FontSize', 10, ...
                                               'BackgroundColor', [0.97, 0.97, 0.97], ...
                                               'ForegroundColor', [0.2, 0.2, 0.2], ...
                                               'Units', 'normalized', ...
                                               'Position', [0.8, 0.35, 0.20, 0.05], ...
                                               'HorizontalAlignment', 'left');
    
    % Calculate Joint Orientation button
    uicontrol('Parent', data.inputPanel, ...
             'Style', 'pushbutton', ...
             'String', 'Calculate JO', ...
             'FontSize', 10, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.3, 0.5, 0.7], ...
             'ForegroundColor', [1, 1, 1], ...
             'Units', 'normalized', ...
             'Position', [0.80, 0.28, 0.12, 0.05], ...
             'Callback', @calculateJointOrientation);
    
    % Joint Orientation Status text
    data.jo_status_text = uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
                                   'String', 'Not Assigned...!', ...
                                   'FontSize', 10, 'FontWeight', 'bold', ...
                                   'BackgroundColor', [0.97, 0.97, 0.97], ...
                                   'ForegroundColor', [0.8, 0.6, 0], ...
                                   'Units', 'normalized', ...
                                   'Position', [0.8, 0.22, 0.25, 0.05], ...
                                   'HorizontalAlignment', 'left');
    
    % Initialize joint orientation score
    data.jo_score = -5; % Default value
    
    % Additional Information Section
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', 'Additional Information:', ...
             'FontSize', 12, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.3, 0.3, 0.6], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.18, 0.3, 0.06], ...
             'HorizontalAlignment', 'left');
    
    % Project Name
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', 'Project Name:', ...
             'FontSize', 10, ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.05, 0.15, 0.05], ...
             'HorizontalAlignment', 'left');
    
    data.project_edit = uicontrol('Parent', data.inputPanel, 'Style', 'edit', ...
                                 'String', 'Tunnel Project', ...
                                 'FontSize', 10, ...
                                 'BackgroundColor', [1, 1, 1], ...
                                 'Units', 'normalized', ...
                                 'Position', [0.18, 0.05, 0.25, 0.05]);
    
    % Location/Chainage
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', 'Location/Chainage:', ...
             'FontSize', 10, ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.5, 0.05, 0.18, 0.05], ...
             'HorizontalAlignment', 'left');
    
    data.location_edit = uicontrol('Parent', data.inputPanel, 'Style', 'edit', ...
                                  'String', 'CH 0+000', ...
                                  'FontSize', 10, ...
                                  'BackgroundColor', [1, 1, 1], ...
                                  'Units', 'normalized', ...
                                  'Position', [0.69, 0.05, 0.25, 0.05]);
    
    % Rock Type
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', 'Rock Type:', ...
             'FontSize', 10, ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.14, 0.13, 0.05], ...
             'HorizontalAlignment', 'left');

    data.rocktype_edit = uicontrol('Parent', data.inputPanel, 'Style', 'edit', ...
                                  'String', 'Granite', ...
                                  'FontSize', 10, ...
                                  'BackgroundColor', [1, 1, 1], ...
                                  'Units', 'normalized', ...
                                  'Position', [0.17, 0.14, 0.25, 0.05]);
    
    % Date
    uicontrol('Parent', data.inputPanel, 'Style', 'text', ...
             'String', 'Date:', ...
             'FontSize', 10, ...
             'BackgroundColor', [0.97, 0.97, 0.97], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.5, 0.14, 0.08, 0.05], ...
             'HorizontalAlignment', 'left');
    
    data.date_edit = uicontrol('Parent', data.inputPanel, 'Style', 'edit', ...
                              'String', datestr(now, 'dd/mm/yyyy'), ...
                              'FontSize', 10, ...
                              'BackgroundColor', [1, 1, 1], ...
                              'Units', 'normalized', ...
                              'Position', [0.59, 0.14, 0.15, 0.05]);
    end

function createResultsPanel()
    % Results panel with enhanced styling
    data.resultsPanel = uipanel('Parent', fig, ...
                          'Title', 'RMR Results', ...
                          'FontSize', 14, ...
                          'FontWeight', 'bold', ...
                          'BackgroundColor', [0.95, 0.98, 0.95], ...
                          'ForegroundColor', [0.2, 0.5, 0.2], ...
                          'BorderType', 'beveledin', ...
                          'BorderWidth', 2, ...
                          'Units', 'normalized', ...
                          'Position', [0.02, 0.18, 0.96, 0.15]);
    
    % RMR Score
    uicontrol('Parent', data.resultsPanel, 'Style', 'text', ...
             'String', 'Total RMR Score:', ...
             'FontSize', 13, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.95, 0.98, 0.95], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.65, 0.25, 0.25], ...
             'HorizontalAlignment', 'left');
    
    data.rmr_score = uicontrol('Parent', data.resultsPanel, 'Style', 'text', ...
                              'String', '50', ...
                              'FontSize', 18, 'FontWeight', 'bold', ...
                              'BackgroundColor', [0.95, 0.98, 0.95], ...
                              'ForegroundColor', [0, 0.5, 0], ...
                              'Units', 'normalized', ...
                              'Position', [0.28, 0.65, 0.08, 0.25], ...
                              'HorizontalAlignment', 'center');
    
    % Rock Class
    uicontrol('Parent', data.resultsPanel, 'Style', 'text', ...
             'String', 'Rock Class:', ...
             'FontSize', 13, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.95, 0.98, 0.95], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.38, 0.65, 0.15, 0.25], ...
             'HorizontalAlignment', 'left');
    
    data.rock_class = uicontrol('Parent', data.resultsPanel, 'Style', 'text', ...
                               'String', 'Class III (Fair Rock)', ...
                               'FontSize', 12, 'FontWeight', 'bold', ...
                               'BackgroundColor', [0.95, 0.98, 0.95], ...
                               'ForegroundColor', [0, 0.5, 0], ...
                               'Units', 'normalized', ...
                               'Position', [0.54, 0.65, 0.4, 0.25], ...
                               'HorizontalAlignment', 'left');
    
    % Stand-up Time
    uicontrol('Parent', data.resultsPanel, 'Style', 'text', ...
             'String', 'Stand-up Time:', ...
             'FontSize', 11, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.95, 0.98, 0.95], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.02, 0.25, 0.18, 0.25], ...
             'HorizontalAlignment', 'left');
    
    data.standup_time = uicontrol('Parent', data.resultsPanel, 'Style', 'text', ...
                                 'String', '1 week for 2.5m span', ...
                                 'FontSize', 10, ...
                                 'BackgroundColor', [0.95, 0.98, 0.95], ...
                                 'ForegroundColor', [0.3, 0.3, 0.3], ...
                                 'Units', 'normalized', ...
                                 'Position', [0.21, 0.25, 0.25, 0.25], ...
                                 'HorizontalAlignment', 'left');
    
    % Cohesion
    uicontrol('Parent', data.resultsPanel, 'Style', 'text', ...
             'String', 'Cohesion:', ...
             'FontSize', 11, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.95, 0.98, 0.95], ...
             'ForegroundColor', [0.2, 0.2, 0.2], ...
             'Units', 'normalized', ...
             'Position', [0.5, 0.25, 0.15, 0.25], ...
             'HorizontalAlignment', 'left');
    
    data.cohesion = uicontrol('Parent', data.resultsPanel, 'Style', 'text', ...
                             'String', '200-300 kPa', ...
                             'FontSize', 10, ...
                             'BackgroundColor', [0.95, 0.98, 0.95], ...
                             'ForegroundColor', [0.3, 0.3, 0.3], ...
                             'Units', 'normalized', ...
                             'Position', [0.66, 0.25, 0.2, 0.25], ...
                             'HorizontalAlignment', 'left');
end

function createButtonPanel()
    % Button panel with enhanced styling
    data.buttonPanel = uipanel('Parent', fig, ...
                         'BackgroundColor', [0.92, 0.92, 0.92], ...
                         'BorderType', 'none', ...
                         'Units', 'normalized', ...
                         'Position', [0.02, 0.02, 0.96, 0.14]);
    
    % Calculate button
    uicontrol('Parent', data.buttonPanel, ...
             'Style', 'pushbutton', ...
             'String', 'Recalculate', ...
             'FontSize', 12, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.2, 0.6, 0.2], ...
             'ForegroundColor', [1, 1, 1], ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.25, 0.18, 0.5], ...
             'Callback', @updateCalculations);
    
    % Export button
    uicontrol('Parent', data.buttonPanel, ...
             'Style', 'pushbutton', ...
             'String', 'Export Report', ...
             'FontSize', 12, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.2, 0.4, 0.7], ...
             'ForegroundColor', [1, 1, 1], ...
             'Units', 'normalized', ...
             'Position', [0.27, 0.25, 0.18, 0.5], ...
             'Callback', @exportReport);
    
    % Clear button
    uicontrol('Parent', data.buttonPanel, ...
             'Style', 'pushbutton', ...
             'String', 'Clear All', ...
             'FontSize', 12, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.8, 0.4, 0.2], ...
             'ForegroundColor', [1, 1, 1], ...
             'Units', 'normalized', ...
             'Position', [0.49, 0.25, 0.18, 0.5], ...
             'Callback', @clearAll);
    
    % Help button
    uicontrol('Parent', data.buttonPanel, ...
             'Style', 'pushbutton', ...
             'String', 'Help', ...
             'FontSize', 12, 'FontWeight', 'bold', ...
             'BackgroundColor', [0.5, 0.5, 0.5], ...
             'ForegroundColor', [1, 1, 1], ...
             'Units', 'normalized', ...
             'Position', [0.71, 0.25, 0.18, 0.5], ...
             'Callback', @showHelp);
end

function resizeCallback(~, ~)
    % Handle window resizing - normalized units handle this automatically
end

    function updateCalculations(~, ~)
    try
        ucs = str2double(get(data.ucs_edit, 'String'));
        if ucs > 250
            ucs_rating = 15;
        elseif ucs > 100
            ucs_rating = 12;
        elseif ucs > 50
            ucs_rating = 7;
        elseif ucs > 25
            ucs_rating = 4;
        elseif ucs > 5
            ucs_rating = 2;
        elseif ucs > 1
            ucs_rating = 1;
        else
            ucs_rating = 0;
        end
        set(data.ucs_text, 'String', sprintf('Rating: %d', ucs_rating));
        
        rqd = str2double(get(data.rqd_edit, 'String'));
        if rqd >= 90
            rqd_rating = 20;
        elseif rqd >= 75
            rqd_rating = 17;
        elseif rqd >= 50
            rqd_rating = 13;
        elseif rqd >= 25
            rqd_rating = 8;
        else
            rqd_rating = 3;
        end
        set(data.rqd_text, 'String', sprintf('Rating: %d', rqd_rating));
        
        js = str2double(get(data.js_edit, 'String'));
        if js > 2
            js_rating = 20;
        elseif js > 0.6
            js_rating = 15;
        elseif js > 0.2
            js_rating = 10;
        elseif js > 0.06
            js_rating = 8;
        else
            js_rating = 5;
        end
        set(data.js_text, 'String', sprintf('Rating: %d', js_rating));
        
        jc_values = [30, 25, 20, 10, 0];
        jc_rating = jc_values(get(data.jc_popup, 'Value'));
        
        gw_values = [15, 10, 7, 4, 0];
        gw_rating = gw_values(get(data.gw_popup, 'Value'));
        
        if isfield(data, 'jo_score')
            jo_adjustment = data.jo_score;
        else
            jo_adjustment = -5;
        end
        
        total_rmr = ucs_rating + rqd_rating + js_rating + jc_rating + gw_rating + jo_adjustment;
        
        set(data.rmr_score, 'String', num2str(total_rmr));
        
        if total_rmr >= 81
            rock_class = 'Class I (Very Good Rock)';
            color = [0, 0.7, 0];
            standup_time = '10 years for 15m span';
            cohesion = '> 400 kPa';
        elseif total_rmr >= 61
            rock_class = 'Class II (Good Rock)';
            color = [0, 0.5, 0];
            standup_time = '1 year for 10m span';
            cohesion = '300-400 kPa';
        elseif total_rmr >= 41
            rock_class = 'Class III (Fair Rock)';
            color = [0.8, 0.8, 0];
            standup_time = '1 week for 5m span';
            cohesion = '200-300 kPa';
        elseif total_rmr >= 21
            rock_class = 'Class IV (Poor Rock)';
            color = [1, 0.5, 0];
            standup_time = '10 hours for 2.5m span';
            cohesion = '100-200 kPa';
        else
            rock_class = 'Class V (Very Poor Rock)';
            color = [1, 0, 0];
            standup_time = '30 minutes for 1m span';
            cohesion = '< 100 kPa';
        end
        
        set(data.rock_class, 'String', rock_class, 'ForegroundColor', color);
        set(data.rmr_score, 'ForegroundColor', color);
        set(data.standup_time, 'String', standup_time);
        set(data.cohesion, 'String', cohesion);
        
    catch
        set(data.rmr_score, 'String', 'Error');
        set(data.rock_class, 'String', 'Check inputs');
    end
end

function calculateJointOrientation(~, ~)
    try
        tunnel_azimuth = str2double(get(data.tunnel_azimuth_edit, 'String'));
        joint_dip = str2double(get(data.joint_dip_edit, 'String'));
        joint_dip_direction = str2double(get(data.joint_dip_direction_edit, 'String'));

        if isnan(tunnel_azimuth) || isnan(joint_dip) || isnan(joint_dip_direction)
            set(data.jo_status_text, 'String', 'Invalid input values', 'ForegroundColor', [1, 0, 0]);
            return;
        end

        % Dip_Dir = joint_dip_direction - tunnel_azimuth;
        Dip_Dir = joint_dip_direction;


        jointData(1) = struct('name', 'Set 1', 'dipDirection', Dip_Dir, 'dip', joint_dip);


        if get(data.show_visualization_checkbox, 'Value')
            results = Orientation_Adjustment_for_Tunnel_RMR(jointData, tunnel_azimuth, 'showGUI', true);
        else
            results = Orientation_Adjustment_for_Tunnel_RMR(jointData, tunnel_azimuth, 'showGUI', false);
        end


        jo_score = results.rmrScore;
        condition = results.category;
        data.jo_score = jo_score;
        
        switch lower(condition)
            case 'very favorable'
                color = [0, 0.7, 0];
            case 'favorable'
                color = [0, 0.5, 0];
            case 'fair'
                color = [0.8, 0.6, 0];
            case 'unfavorable'
                color = [1, 0.5, 0];
            case 'very unfavorable'
                color = [1, 0, 0];
            otherwise
                color = [0.3, 0.3, 0.3];
        end
        
        set(data.jo_status_text, 'String', sprintf('Score: %d (%s)', jo_score, condition), ...
            'ForegroundColor', color);
        
        updateCalculations();
        
    catch
        set(data.jo_status_text, 'String', 'Calculation error', 'ForegroundColor', [1, 0, 0]);
    end
end


function exportReport(~, ~)
    try
        [filename, pathname] = uiputfile('*.txt', 'Save RMR Report');
        if filename ~= 0
            fid = fopen(fullfile(pathname, filename), 'w');
            
            fprintf(fid, '===========================================\n');
            fprintf(fid, '    TUNNEL ROCK MASS RATING (RMR) REPORT\n');
            fprintf(fid, '===========================================\n\n');
            
            fprintf(fid, 'Project: %s\n', get(data.project_edit, 'String'));
            fprintf(fid, 'Location: %s\n', get(data.location_edit, 'String'));
            fprintf(fid, 'Rock Type: %s\n', get(data.rocktype_edit, 'String'));
            fprintf(fid, 'Date: %s\n\n', get(data.date_edit, 'String'));
            
            fprintf(fid, 'RMR PARAMETERS:\n');
            fprintf(fid, '1. UCS: %s MPa - Rating: %s\n', ...
                get(data.ucs_edit, 'String'), get(data.ucs_text, 'String'));
            fprintf(fid, '2. RQD: %s%% - Rating: %s\n', ...
                get(data.rqd_edit, 'String'), get(data.rqd_text, 'String'));
            fprintf(fid, '3. Joint Spacing: %s m - Rating: %s\n', ...
                get(data.js_edit, 'String'), get(data.js_text, 'String'));
            
            jc_strings = get(data.jc_popup, 'String');
            fprintf(fid, '4. Joint Condition: %s\n', ...
                jc_strings{get(data.jc_popup, 'Value')});
            
            gw_strings = get(data.gw_popup, 'String');
            fprintf(fid, '5. Groundwater: %s\n', ...
                gw_strings{get(data.gw_popup, 'Value')});
            
            fprintf(fid, 'RESULTS:\n');
            fprintf(fid, 'Total RMR Score: %s\n', get(data.rmr_score, 'String'));
            fprintf(fid, 'Rock Class: %s\n', get(data.rock_class, 'String'));
            fprintf(fid, 'Stand-up Time: %s\n', get(data.standup_time, 'String'));
            fprintf(fid, 'Cohesion: %s\n', get(data.cohesion, 'String'));
            
            fclose(fid);
            msgbox('Report exported successfully!', 'Export Complete');
        end
    catch
        msgbox('Error exporting report!', 'Export Error', 'error');
    end
end

function clearAll(~, ~)
    set(data.ucs_edit, 'String', '');
    set(data.rqd_edit, 'String', '');
    set(data.js_edit, 'String', '');
    set(data.jc_popup, 'Value', 1);
    set(data.gw_popup, 'Value', 1);
    set(data.project_edit, 'String', '');
    set(data.location_edit, 'String', '');
    set(data.rocktype_edit, 'String', '');
    set(data.date_edit, 'String', datestr(now, 'dd/mm/yyyy'));
    updateCalculations();
end

function showHelp(~, ~)
    help_text = {
        'TUNNEL RMR CALCULATOR HELP';
        '';
        'This tool calculates the Rock Mass Rating (RMR) for tunnel design.';
        '';
        'INPUT PARAMETERS:';
        '1. UCS: Uniaxial Compressive Strength in MPa';
        '2. RQD: Rock Quality Designation as percentage';
        '3. Joint Spacing: Average spacing between joints in meters';
        '4. Joint Condition: Select from dropdown menu';
        '5. Groundwater: Select groundwater condition';
        '6. Joint Orientation: Adjustment for tunnel orientation';
        '';
        'RMR CLASSES:';
        'Class I (81-100): Very Good Rock';
        'Class II (61-80): Good Rock';
        'Class III (41-60): Fair Rock';
        'Class IV (21-40): Poor Rock';
        'Class V (0-20): Very Poor Rock';
        '';
        'FEATURES:';
        '- Real-time calculation';
        '- Export reports to text file';
        '- Color-coded results';
        '- Engineering properties estimation';
        '- Resizable interface';
    };
    
    msgbox(help_text, 'RMR Calculator Help', 'help');
end

end